// Generated by CoffeeScript 1.7.1
(function() {
  var dynamicWebService;

  dynamicWebService = '.';

  $(document).ready(function() {
    var js, settleFile;
    js = '';
    settleFile = function(js) {
      var i, msg, se, semester, _ref, _results;
      console.log(js.detail);
      _ref = js.detail;
      _results = [];
      for (semester in _ref) {
        se = _ref[semester];
        console.log(semester);
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (i in se) {
            msg = se[i];
            console.log(msg.title);
            console.log(msg.score);
            _results1.push(console.log(msg.grade));
          }
          return _results1;
        })());
      }
      return _results;
    };
    return $('#search-btn').click(function() {
      var number, url;
      $('.jumbotron').slideUp();
      number = $('#input1').val();
      console.log(number);
      number = '1205030209.html';
      url = dynamicWebService + '/api/score/' + number;
      $.get(url, (function(result, status, xhr) {
        console.log(result + status);
        return settleFile(result);
      }), 'json');
      return false;
    });
  });

}).call(this);
